import { createContext, useContext, useEffect, useMemo, useState } from 'react';

const translations = {
  ar: {
    appName: 'نظام نقاط البيع',
    sale: 'البيع',
    shifts: 'الصندوق',
    returns: 'الإرجاع',
    account: 'حسابي',
    dashboard: 'لوحة التحكم',
    products: 'المنتجات',
    users: 'المستخدمين',
    permissions: 'الصلاحيات',
    settings: 'الإعدادات',
    admin: 'مدير',
    cashier: 'كاشير',
    logout: 'تسجيل خروج',
    languageName: 'English',
    loginTitle: 'تسجيل الدخول',
    username: 'اسم المستخدم',
    password: 'كلمة السر',
    login: 'دخول',
    loggingIn: 'جارٍ الدخول...',
    loginError: 'حدث خطأ، حاول مجدداً',
    myAccount: 'حسابي',
    name: 'الاسم',
    email: 'البريد الإلكتروني',
    changePassword: 'تغيير كلمة السر',
    currentPassword: 'كلمة السر الحالية',
    newPassword: 'كلمة السر الجديدة',
    confirmPassword: 'تأكيد كلمة السر',
    saveChanges: 'حفظ التغييرات',
    saving: 'جارٍ الحفظ...',
    accountUpdated: 'تم تحديث الحساب بنجاح',
    accountUpdateError: 'حدث خطأ أثناء تحديث الحساب',
    loading: 'جارٍ التحميل...',
    savingSettings: 'جارٍ الحفظ...',
    settingsTitle: 'الإعدادات العامة',
    taxEnabled: 'تفعيل الضريبة',
    taxRateLabel: 'نسبة الضريبة (%)',
    storeNameLabel: 'اسم المحل',
    currencyLabel: 'العملة',
    invoiceHeaderLabel: 'ترويسة الفاتورة',
    lowStockThresholdLabel: 'الحد الأدنى للتنبيه بنقص المخزون',
    settingsSaved: 'تم حفظ الإعدادات بنجاح',
    settingsLoadError: 'حدث خطأ أثناء تحميل الإعدادات',
    settingsSaveError: 'حدث خطأ أثناء حفظ الإعدادات',
    openShiftTitle: 'لا توجد وردية مفتوحة حالياً',
    openShiftMessage: 'يجب فتح وردية أولاً لبدء البيع',
    openShiftButton: 'فتح وردية',
    openingBalance: 'رصيد بداية الوردية',
    opening: 'فتح وردية',
    verifyingShift: 'جارٍ التحقق من الوردية الحالية...',
    currentInvoice: 'الفاتورة الحالية',
    productsTitle: 'المنتجات',
    noProductsAdded: 'لا توجد منتجات مضافة',
    subtotalLabel: 'المجموع الفرعي',
    paymentMethodLabel: 'طريقة الدفع',
    paymentCash: 'نقدي',
    paymentCard: 'بطاقة',
    checkout: 'إتمام البيع',
    cancel: 'إلغاء',
    completingSale: 'جارٍ الإتمام...',
    returnTitle: 'إرجاع منتج',
    search: 'بحث',
    invoiceNumber: 'رقم الفاتورة',
    mustSelectReturnQuantity: 'يجب تحديد كمية إرجاع لمنتج واحد على الأقل',
    returnConfirmed: 'تم إنشاء المرتجع بنجاح — المبلغ:',
    managerConfirmationRequired: 'هذه العملية تتطلب تأكيد المدير',
    managerUsername: 'اسم مستخدم المدير',
    managerPassword: 'كلمة سر المدير',
    submitReturn: 'تنفيذ الإرجاع',
    managerOnly: 'هذه الصفحة متاحة للمدير فقط',
    dashboardLoadError: 'حدث خطأ أثناء تحميل بيانات لوحة التحكم',
    shiftsPageTitle: 'الصندوق — إدارة الوردية',
    shiftClosed: 'تم إغلاق الوردية',
    expectedBalanceLabel: 'الرصيد المتوقع',
    countedBalanceLabel: 'الرصيد المعدود',
    discrepancyLabel: 'الفرق',
    matchingText: 'متطابق',
    surplusText: 'زيادة',
    shortageText: 'نقص',
    shiftNotOpenTitle: 'لا توجد وردية مفتوحة حالياً',
    shiftOpenButton: 'فتح وردية',
    shiftOpenedAtLabel: 'بدأت في',
    cashierLabel: 'الكاشير',
    shiftMovements: 'حركات الصندوق',
    saleType: 'بيع',
    returnType: 'إرجاع',
    closeShiftHeading: 'إغلاق الوردية',
    closingShift: 'جاري الإغلاق...',
    cashiersManagement: 'إدارة المستخدمين',
    addCashierButton: '+ إضافة موظف جديد',
    tableName: 'الاسم',
    tableUsername: 'اسم المستخدم',
    tableEmail: 'البريد',
    tableRole: 'الدور',
    tableStatus: 'الحالة',
    activeStatus: 'مفعّل',
    inactiveStatus: 'معطّل',
    enableAction: 'تفعيل',
    disableAction: 'تعطيل',
    userCreationSuccess: 'تم إنشاء الحساب بنجاح',
    tempPasswordLabel: 'كلمة السر المؤقتة',
    temporaryPasswordNote: 'سلّمها للموظف الآن — لن تظهر مرة أخرى.',
    closeModal: 'إغلاق',
    addUserTitle: 'إضافة موظف جديد',
    fullNamePlaceholder: 'الاسم الكامل',
    usernamePlaceholder: 'اسم المستخدم',
    emailPlaceholder: 'البريد الإلكتروني',
    roleCashier: 'كاشير',
    roleAdmin: 'مدير',
    save: 'حفظ',
    productsManagement: 'إدارة المنتجات',
    addProductButton: '+ إضافة منتج',
    productNamePlaceholder: 'اسم المنتج',
    productCategoryPlaceholder: 'التصنيف (اختياري)',
    productPricePlaceholder: 'السعر',
    productStockPlaceholder: 'الكمية الأولية',
    productMinStockPlaceholder: 'الحد الأدنى للتنبيه',
    product: 'المنتج',
    quantity: 'الكمية',
    revenue: 'الإيراد',
    amount: 'القيمة',
    productSaved: 'تم حفظ المنتج بنجاح',
    productLowStockBadge: 'مخزون منخفض',
    availableLabel: 'متوفر:',
    permissionsTitle: 'إدارة الصلاحيات',
    permissionsDescription: 'تحديد الكاشيرين المسموح لهم بتنفيذ عمليات الإرجاع دون الحاجة لتأكيد المدير.',
    noCashiersYet: 'لا يوجد حسابات كاشير بعد.',
    returnWithoutApproval: 'إرجاع بدون موافقة',
    activeLabel: 'فعال',
    inactiveLabel: 'معطل',
    loadingPermissionsError: 'تعذر تحميل بيانات الصلاحيات',
    updatePermissionError: 'تعذر تحديث الصلاحية',
    dashboardTitle: 'لوحة التحكم',
    today: 'اليوم',
    yesterday: 'أمس',
    thisWeek: 'هذا الأسبوع',
    lastWeek: 'الأسبوع الماضي',
    thisMonth: 'هذا الشهر',
    lastMonth: 'الشهر الماضي',
    customPeriod: 'فترة مخصصة',
    insufficientData: 'لا توجد بيانات كافية لهذه الفترة',
    totalSalesLabel: 'إجمالي المبيعات',
    invoicesCountLabel: 'عدد الفواتير',
    totalReturnsLabel: 'إجمالي المرتجعات',
    netRevenueLabel: 'صافي الإيراد',
    cashierPerformanceTitle: 'أداء الكاشيرين',
    cashierTitle: 'الكاشير',
    totalLabel: 'الإجمالي',
    topSellingTitle: 'الأكثر مبيعاً',
    topReturnedTitle: 'الأكثر ترجيعاً',
    directionNetRevenueLabel: 'اتجاه صافي الإيراد',
    noDataLabel: 'لا توجد بيانات',
    invoiceSuccess: 'تم إتمام البيع بنجاح',
    print: 'طباعة',
    newInvoice: 'فاتورة جديدة',
    invoiceNumberLabel: 'فاتورة رقم',
    totalAmountLabel: 'الإجمالي',
    taxLabel: 'الضريبة',
    paymentMethodText: 'طريقة الدفع',
    paymentCashText: 'نقدي',
    paymentCardText: 'بطاقة',
    errorOccurred: 'حدث خطأ',
    changePasswordTitle: 'تعيين كلمة سر جديدة',
    savePassword: 'حفظ',
    passwordToggleShow: '😐',
    passwordToggleHide: '😑',
  },
  en: {
    appName: 'Point of Sale',
    sale: 'Sale',
    shifts: 'Cashbox',
    returns: 'Returns',
    account: 'My Account',
    dashboard: 'Dashboard',
    products: 'Products',
    users: 'Users',
    permissions: 'Permissions',
    settings: 'Settings',
    admin: 'Admin',
    cashier: 'Cashier',
    logout: 'Logout',
    languageName: 'العربية',
    loginTitle: 'Login',
    username: 'Username',
    password: 'Password',
    login: 'Login',
    loggingIn: 'Logging in...',
    loginError: 'Something went wrong, please try again',
    myAccount: 'My Account',
    name: 'Name',
    email: 'Email',
    changePassword: 'Change Password',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm Password',
    saveChanges: 'Save Changes',
    saving: 'Saving...',
    accountUpdated: 'Account updated successfully',
    accountUpdateError: 'Failed to update account',
    loading: 'Loading...',
    savingSettings: 'Saving...',
    settingsTitle: 'General Settings',
    taxEnabled: 'Enable Tax',
    taxRateLabel: 'Tax Rate (%)',
    storeNameLabel: 'Store Name',
    currencyLabel: 'Currency',
    invoiceHeaderLabel: 'Invoice Header',
    lowStockThresholdLabel: 'Low Stock Alert Threshold',
    settingsSaved: 'Settings saved successfully',
    settingsLoadError: 'Failed to load settings',
    settingsSaveError: 'Failed to save settings',
    openShiftTitle: 'No open shift currently',
    openShiftMessage: 'You must open a shift before starting sales',
    openShiftButton: 'Open Shift',
    openingBalance: 'Opening Balance',
    opening: 'Open Shift',
    verifyingShift: 'Checking current shift...',
    currentInvoice: 'Current Invoice',
    productsTitle: 'Products',
    noProductsAdded: 'No products added',
    subtotalLabel: 'Subtotal',
    paymentMethodLabel: 'Payment Method',
    paymentCash: 'Cash',
    paymentCard: 'Card',
    checkout: 'Checkout',
    cancel: 'Cancel',
    completingSale: 'Completing...',
    returnTitle: 'Return Product',
    search: 'Search',
    invoiceNumber: 'Invoice Number',
    mustSelectReturnQuantity: 'You must select a return quantity for at least one item',
    returnConfirmed: 'Return created successfully — amount:',
    managerConfirmationRequired: 'This action requires manager confirmation',
    managerUsername: 'Manager Username',
    managerPassword: 'Manager Password',
    submitReturn: 'Submit Return',
    managerOnly: 'This page is available to managers only',
    dashboardLoadError: 'Failed to load dashboard data',
    shiftsPageTitle: 'Cashbox — Shift Management',
    shiftClosed: 'Shift closed successfully',
    expectedBalanceLabel: 'Expected Balance',
    countedBalanceLabel: 'Counted Balance',
    discrepancyLabel: 'Discrepancy',
    matchingText: 'Matching',
    surplusText: 'Surplus',
    shortageText: 'Shortage',
    shiftNotOpenTitle: 'No open shift currently',
    shiftOpenButton: 'Open Shift',
    shiftOpenedAtLabel: 'Started at',
    cashierLabel: 'Cashier',
    shiftMovements: 'Cash movements',
    saleType: 'Sale',
    returnType: 'Return',
    closeShiftHeading: 'Close Shift',
    closingShift: 'Closing...',
    cashiersManagement: 'Users Management',
    addCashierButton: '+ Add New Staff',
    tableName: 'Name',
    tableUsername: 'Username',
    tableEmail: 'Email',
    tableRole: 'Role',
    tableStatus: 'Status',
    activeStatus: 'Active',
    inactiveStatus: 'Inactive',
    enableAction: 'Enable',
    disableAction: 'Disable',
    userCreationSuccess: 'User created successfully',
    tempPasswordLabel: 'Temporary password',
    temporaryPasswordNote: 'Give it to the staff now — it will not show again.',
    closeModal: 'Close',
    addUserTitle: 'Add New Staff',
    fullNamePlaceholder: 'Full Name',
    usernamePlaceholder: 'Username',
    emailPlaceholder: 'Email',
    roleCashier: 'Cashier',
    roleAdmin: 'Admin',
    save: 'Save',
    productsManagement: 'Products Management',
    addProductButton: '+ Add Product',
    productNamePlaceholder: 'Product Name',
    productCategoryPlaceholder: 'Category (optional)',
    productPricePlaceholder: 'Price',
    productStockPlaceholder: 'Initial Quantity',
    productMinStockPlaceholder: 'Low Stock Threshold',
    product: 'Product',
    quantity: 'Quantity',
    revenue: 'Revenue',
    amount: 'Amount',
    productSaved: 'Product saved successfully',
    productLowStockBadge: 'Low stock',
    availableLabel: 'Available:',
    permissionsTitle: 'Permissions Management',
    permissionsDescription: 'Choose cashiers who can process returns without manager approval.',
    noCashiersYet: 'No cashier accounts yet.',
    returnWithoutApproval: 'Return without approval',
    activeLabel: 'Active',
    inactiveLabel: 'Inactive',
    loadingPermissionsError: 'Failed to load permissions data',
    updatePermissionError: 'Failed to update permission',
    dashboardTitle: 'Dashboard',
    today: 'Today',
    yesterday: 'Yesterday',
    thisWeek: 'This week',
    lastWeek: 'Last week',
    thisMonth: 'This month',
    lastMonth: 'Last month',
    customPeriod: 'Custom',
    insufficientData: 'Not enough data for this period',
    totalSalesLabel: 'Total Sales',
    invoicesCountLabel: 'Invoice Count',
    totalReturnsLabel: 'Total Returns',
    netRevenueLabel: 'Net Revenue',
    cashierPerformanceTitle: 'Cashier performance',
    cashierTitle: 'Cashier',
    totalLabel: 'Total',
    topSellingTitle: 'Top Selling',
    topReturnedTitle: 'Top Returned',
    directionNetRevenueLabel: 'Net revenue trend',
    noDataLabel: 'No data',
    invoiceSuccess: 'Sale completed successfully',
    print: 'Print',
    newInvoice: 'New Invoice',
    invoiceNumberLabel: 'Invoice #',
    totalAmountLabel: 'Total',
    taxLabel: 'Tax',
    paymentMethodText: 'Payment Method',
    paymentCashText: 'Cash',
    paymentCardText: 'Card',
    errorOccurred: 'An error occurred',
    changePasswordTitle: 'Set New Password',
    savePassword: 'Save',
    passwordToggleShow: '😐',
    passwordToggleHide: '😑',
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem('language') || 'ar');

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
  }, [language]);

  const value = useMemo(() => {
    const t = (key) => translations[language][key] ?? translations.ar[key] ?? key;
    const toggleLanguage = () => setLanguage((current) => (current === 'ar' ? 'en' : 'ar'));

    return {
      language,
      direction: language === 'ar' ? 'rtl' : 'ltr',
      t,
      toggleLanguage,
    };
  }, [language]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
